[package]
name = "resume-builder"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [ "Stephen Waits <steve@waits.net>" ]
license = "MIT"
description = "A modern résumé/curriculum vitæ template, build your resume quickly!"
categories = [ "cv" ]
disciplines = [ "business", "communication" ]
keywords = [ "resume", "curriculum", "vitae", "cv" ]
repository = "https://github.com/swaits/typst-collection"
exclude = [ "thumbnail.png", "tests" ]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
